### ISSUE TITLE
theano cross-compiler tests don't pass

### ISSUE THREAD

**Issue by krivard** [TeamCohen/TensorLog#9]
TestXCProPPR.testLearn shows a final accuracy of 0.57 instead of 1.0:

```
$ python -m unittest testxcomp.TestXCProPPR.testLearn
initial train data loss   (0, 0)	0.0036290430711095703
initial test data loss   (0, 0)	0.0036290429600314314
initial train accuracy 0.545454545455
initial test accuracy 0.571428571429
params to optimize [('weighted', 1)]
vars to optimize [v__weighted]
final train data loss   (0, 0)	0.003541829498158074
final test data loss   (0, 0)	0.003574505589971252
final train accuracy 0.636363636364
final test accuracy 0.571428571429
F
======================================================================
FAIL: testLearn (testxcomp.TestXCProPPR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testxcomp.py", line 563, in testLearn
    self.assertTrue(acc2>=0.9)
AssertionError: False is not true

```

TestXCProPPR.testGradMatrix shows w * w0 > 0:

```
$ python -m unittest testxcomp.TestXCProPPR.testGradMatrix
loss 7.62464 crossEnt 7.62464 reg 0
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '12440' (I am process '10121')
WARNING:theano.gof.compilelock:Overriding existing lock by dead process '12440' (I am process '10121')
F
======================================================================
FAIL: testGradMatrix (testxcomp.TestXCProPPR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testxcomp.py", line 486, in testGradMatrix
    self.assertTrue(w[i,j] * w0[i,j] <= 0.0,"i=%d,j=%d,w=%g,w0=%g"%(i,j,w[i,j],w0[i,j]))
AssertionError: i=0,j=138,w=4.5937e-05,w0=5.66244e-07

```

**Comment by krivard** [comment]
We've turned off the theano listing in xctargets so it won't run during tests. The theano cross-compiler isn't a priority.
